# -*- mode: ruby -*-
# vi: set ft=ruby :

file_to_disk_srvr1 = './tmp/large_disk_srvr1.vdi'

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "everlast"
	config.vm.network "private_network", ip: "192.168.2.43"
	config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
		unless File.exist?(file_to_disk_srvr1)
			vb.customize ['createhd', '--filename', file_to_disk_srvr1, '--size', 80 * 1024]
		end
		vb.customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk_srvr1]
		vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
		vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
	end
end