# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

    config.vm.network "private_network", ip: "192.168.2.165"
  #	config.vm.network "public_network", ip: "192.168.1.200"
    config.vm.provision :shell, path: "bootstrap.sh"
  
end
