# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#	config.vm.define "client" do |client|
#		client.vm.box = "centos"
#		client.vm.network "private_network", ip: "192.168.2.151"
#		client.vm.provision :shell, path: "bootstrap_client.sh"
#		client.vm.hostname = "client"
#		client.vm.provider "virtualbox" do |vb|
#			vb.memory = "2048"
#		end
#	end

	config.vm.define "server" do |server|
		server.vm.box = "centos"
		server.vm.network "public_network", :mac => "0800271E4DC0"
#		server.vm.network "public_network"
		server.vm.provision :shell, path: "bootstrap_server.sh"
		server.vm.hostname = "server"
		server.vm.provider "virtualbox" do |vb|
			vb.memory = "1024"
		end
	end
end
